<center><h1 style="color:blue">K Fold Cross Validation</h1></center>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
import numpy as np

In [2]:
digits = load_digits()

In [3]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

<h1>Logistic Regression</h1>

In [4]:
lr = LogisticRegression(max_iter=500)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9740740740740741

In [5]:
lr = LogisticRegression(solver='liblinear')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9685185185185186

<h1>SVM</h1>

In [6]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [7]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.4148148148148148

<h1>Random Forest</h1>

In [8]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9685185185185186

<h1 style="color:purple">K-Fold Cross Validation</h1>

<h3>Basic Example</h3>

In [9]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


<h3>Use KFold for our digits example</h3>

In [11]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [12]:
get_score(LogisticRegression(max_iter=500),X_train,X_test,y_train,y_test)

0.9740740740740741

In [13]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9888888888888889

In [14]:
get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test)

0.9611111111111111

In [15]:
folds = StratifiedKFold(n_splits=3)

In [16]:
scores_l = []
scores_svm = []
scores_rf = []
for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index], \
                                    digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=500),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

In [17]:
scores_l

[0.9198664440734557, 0.9432387312186978, 0.9165275459098498]

In [18]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [19]:
scores_rf

[0.9449081803005008, 0.9632721202003339, 0.9382303839732888]

In [20]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [21]:
scores_l

[0.9198664440734557, 0.9432387312186978, 0.9165275459098498]

In [22]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [23]:
scores_rf

[0.9315525876460768, 0.9315525876460768, 0.9181969949916527]

<h1 style="color:purple">cross_val_score function</h1>

<b>Logistic regression model performance using cross_val_score

In [24]:
cross_val_score(LogisticRegression(max_iter=500),digits.data,digits.target,cv=3)

array([0.91986644, 0.94323873, 0.91652755])

In [25]:
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

<b>SVM model performance using cross_val_score

In [26]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [27]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

<b>Random Forest model performance using cross_val_score

In [28]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.93489149, 0.95158598, 0.92487479])

In [29]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93989983, 0.94156928, 0.92487479])

cross_val_score uses stratifield kfold by default

<h1 style="color:purple">Parameter tunning using k fold cross validation</h1>

In [30]:
scores1=cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target,cv=3)
np.average(scores1)

0.8580968280467447

In [31]:
scores2=cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target,cv=3)
np.average(scores2)

0.9271007234279355

In [32]:
scores3=cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target,cv=3)
np.average(scores3)

0.9332220367278797

In [33]:
scores4=cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)
np.average(scores4)

0.9365609348914857

In [34]:
scores5=cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target,cv=3)
np.average(scores5)

0.9387868670005565

In [35]:
scores6=cross_val_score(RandomForestClassifier(n_estimators=60),digits.data, digits.target,cv=3)
np.average(scores6)

0.9376739009460211

##### Here we used cross_val_score to fine tune our random forest classifier and figured that having around 50 trees in random forest gives best result.